# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Diagrams

on:
  push:
    branches: [ "main" ]
    paths:
    - 'diagrams/**'
    - '!/docs/**'
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install graphviz
        pip install diagrams   
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1          
    - name: Remove legacy images
      run: |               
        echo ${{ github.job }} > ${{ github.workspace }}/docs/assets/filebase
        # removing files
        rm -f ${{ github.workspace }}/docs/assets/*.png                        
    - name: Commit diagrams image changes
      run: |
        git config --global user.name 'Albert Tanure'
        git config --global user.email 'tanure@live.com'
        git add .
        git commit -am "Update generated diagrams images"
        git push
    - name: Generating diagrams
      run: |
        python ${{ github.workspace }}/diagrams/DiagramBuilder.py
    - name: Update assets folder
      run: |                               
        # moving files
        mv *.png ${{ github.workspace }}/docs/assets           
    - name: Commit diagrams image changes
      run: |
        git config --global user.name 'Albert Tanure'
        git config --global user.email 'tanure@live.com'
        git add .
        git commit -am "Update generated diagrams images"
        git push
