# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Diagrams

on:
  push:
    branches: [ "main" ]
    paths:
    - 'diagrams/**'
    - '!/docs/**'
    
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        #pip install graphviz
        pip install diagrams   
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1      
    - name: Generating diagrams
      run: |
        sh ./diagrams/makefile.sh
    - name: Update assets folder
      run: |
        # moving files
        rm ${{ github.workspace }}/docs/assets/*.png
        mv *.png ${{ github.workspace }}/docs/assets
        git status
    - name: Obter o branch atual
      run: |
        branch=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        echo "O branch atual é: $branch"
    - name: Commit diagrams image changes
      run: |
        git config --global user.name 'Albert Tanure'
        git config --global user.email 'tanure@live.com'
        git add .
        git commit -am "Update generated diagrams images"
        git push

